import { t } from 'i18next';

const ERORR_CODES = {
  PERMISSION_DENIED: 1,
  POSITION_UNAVAILABLE: 2,
  TIMEOUT: 3
};

export const ERROR_TEXTS = {
  [ERORR_CODES.PERMISSION_DENIED]: t('Home:PERMISSION_DENIED'),
  [ERORR_CODES.POSITION_UNAVAILABLE]: t('Home:POSITION_UNAVAILABLE'),
  [ERORR_CODES.TIMEOUT]: t('Home:TIMEOUT')
};

export const DEFAULT_TIME_SHOW_NOTI = 3000;
